### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/etc/letsencrypt'

### ISSUE THREAD

**Issue by zopyx** [veit/userland-certbot#4]
ajung@dev.zopyx.com:~/src/userland-certbot> bin/certbot --register
An unexpected error occurred:
OSError: [Errno 13] Permission denied: '/etc/letsencrypt'
Please see the logfile 'certbot.log' for more details.

**Comment by veit** [comment]
You should use `bin/certbot-register`, or if dialog isn’t installed `bin/certbot-register --text`.

**Comment by MichaelHierweck** [comment]
Closing as we added a related note to README.rst ([Commit](https://github.com/veit/userland-certbot/commit/48af34259f21308a8bcf099b03591b9d988987bb)).
Please feel free to reopen this issue if the problem still appears in your setup when invoking bin/certbot-runner instead.
